import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
  ArrowLeft, CheckCircle, Image as ImageIcon, Gamepad2, Brush, 
  Coins, Diamond, Box, ExternalLink, Code, Layers, Zap 
} from 'lucide-react';

const nftCaseStudies = [
  {
    id: 0,
    client: "MetaFashion",
    title: "Phygital Wearables",
    stat: "$1.2M",
    statLabel: "Primary Sales Volume",
    icon: <ImageIcon className="w-12 h-12 text-pink-400" />,
    color: "pink",
    tags: ["Fashion", "AR Filters", "Physical-Backed"],
    contract: "0x7a2...891b",
    challenge: "MetaFashion wanted to launch a luxury streetwear line where every physical hoodie came with a digital twin usable in the Metaverse. They needed a 'chip-to-chain' verification system to prevent counterfeits.",
    solution: "We developed an NFC-enabled ERC-721 smart contract. Scanning the physical hoodie's tag mints the NFT to the user's wallet. The NFT metadata includes 3D asset files compatible with Decentraland and Sandbox.",
    results: [
      "Sold out 5,000 units in 48 minutes.",
      "Secondary market royalties generated $300k extra revenue.",
      "Zero counterfeit claims reported post-launch."
    ]
  },
  {
    id: 1,
    client: "GameVerse",
    title: "Cross-Chain Gaming Assets",
    stat: "500k+",
    statLabel: "Items Minted",
    icon: <Gamepad2 className="w-12 h-12 text-cyan-400" />,
    color: "cyan",
    tags: ["GameFi", "Interoperability", "Sidechain"],
    contract: "0x3b1...229a",
    challenge: "Players in GameVerse were frustrated by high gas fees when trading in-game swords and skins. The game needed a high-speed, zero-gas environment that could still bridge assets back to Ethereum Mainnet.",
    solution: "We built a custom AppChain (Avalanche Subnet) specifically for GameVerse logic. A 'Lock-and-Mint' bridge allows players to move assets to Ethereum only when they want to sell on OpenSea, keeping gameplay interactions free.",
    results: [
      "1.5 Million transactions processed with $0 gas cost to players.",
      "Player retention increased by 40% due to true asset ownership.",
      "Marketplace volume hit $5M in the first quarter."
    ]
  },
  {
    id: 2,
    client: "ArtDAO",
    title: "Generative Art Platform",
    stat: "15m",
    statLabel: "Sellout Time",
    icon: <Brush className="w-12 h-12 text-purple-400" />,
    color: "purple",
    tags: ["Generative Art", "Dutch Auction", "DAO"],
    contract: "0x9c4...110f",
    challenge: "ArtDAO wanted to release a collection of 10,000 unique pieces generated by a complex p5.js algorithm. Storing the artwork on centralized servers was against their ethos; they needed full on-chain provenance.",
    solution: "We stored the generation script directly on-chain using Ethereum's storage. The visual is rendered live in the browser by pulling the seed from the transaction hash. We also implemented an optimized ERC721A contract to minimize minting gas.",
    results: [
      "100% on-chain data storage (no IPFS dependency).",
      "Gas fees saved: ~$400,000 for the community.",
      "Raised $2.5M for the DAO treasury."
    ]
  }
];

const NFTCaseStudyPage = () => {
  const { id } = useParams();
  const data = nftCaseStudies[Number(id)];

  if (!data) return <div className="text-white pt-32 text-center">Case Study Not Found</div>;

  const colors = {
    pink: "from-pink-500",
    cyan: "from-cyan-500",
    purple: "from-purple-500",
  };

  const borderColors = {
    pink: "border-pink-500/30",
    cyan: "border-cyan-500/30",
    purple: "border-purple-500/30",
  };

  const textColors = {
    pink: "text-pink-400",
    cyan: "text-cyan-400",
    purple: "text-purple-400",
  };

  return (
    <div className="min-h-screen bg-[#020617] pt-24 pb-20 selection:bg-pink-500/30 font-sans relative overflow-hidden">
      
      {/* Background Decor */}
      <div className="fixed top-0 left-0 w-full h-full pointer-events-none">
         <div className={`absolute top-[-20%] right-[-10%] w-[800px] h-[800px] rounded-full blur-[150px] bg-${data.color}-600/10`}></div>
         <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-[0.03]"></div>
      </div>

      {/* Header */}
      <div className="max-w-5xl mx-auto px-4 relative z-10">
        <Link to="/nft" className="inline-flex items-center text-slate-400 hover:text-white mb-8 transition-colors group">
          <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" /> Back to Marketplace
        </Link>
        
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-12"
        >
          <div>
            <div className="flex items-center gap-3 mb-4">
               <div className={`px-3 py-1 rounded-full border ${borderColors[data.color]} bg-white/5 text-xs font-mono ${textColors[data.color]} uppercase tracking-widest`}>
                  {data.client}
               </div>
               <div className="px-3 py-1 rounded-full border border-white/10 bg-white/5 text-xs font-mono text-slate-400 flex items-center gap-2">
                  <Code className="w-3 h-3" /> Contract Verified
               </div>
            </div>
            <h1 className="text-5xl md:text-7xl font-black text-white tracking-tighter mb-2">{data.title}</h1>
          </div>
          
          {/* Smart Contract Address Pill */}
          <div className="hidden md:flex items-center gap-2 px-4 py-2 rounded-xl bg-[#0A0A0A] border border-white/10 font-mono text-sm text-slate-400 hover:border-white/30 transition-colors cursor-pointer">
             <span className={`w-2 h-2 rounded-full bg-${data.color}-500 animate-pulse`}></span>
             {data.contract}
             <ExternalLink className="w-3 h-3 ml-2" />
          </div>
        </motion.div>
      </div>

      {/* Main Content */}
      <div className="max-w-5xl mx-auto px-4 relative z-10">
        
        {/* 1. KEY STATS BANNER */}
        <motion.div 
           initial={{ scale: 0.95, opacity: 0 }}
           animate={{ scale: 1, opacity: 1 }}
           className={`relative overflow-hidden rounded-3xl bg-gradient-to-r ${colors[data.color]} to-slate-900 p-[1px] mb-16 shadow-2xl`}
        >
          <div className="bg-[#0A0A0A]/95 backdrop-blur-xl rounded-[23px] p-8 md:p-12 flex flex-col md:flex-row items-center justify-between gap-8 relative">
             {/* Animated Glitch Background */}
             <div className="absolute inset-0 bg-[linear-gradient(45deg,transparent_25%,rgba(255,255,255,0.05)_50%,transparent_75%)] bg-[length:250%_250%] animate-shine pointer-events-none"></div>

             <div className="relative z-10">
               <div className="flex items-center gap-2 text-slate-400 uppercase tracking-widest text-xs font-bold mb-3">
                  <Diamond className="w-4 h-4" /> Collection Performance
               </div>
               <div className={`text-6xl md:text-7xl font-black text-transparent bg-clip-text bg-gradient-to-r ${colors[data.color]} to-white`}>
                 {data.stat}
               </div>
             </div>
             
             <div className="text-right relative z-10">
               <div className="text-2xl font-bold text-white mb-1">{data.statLabel}</div>
               <div className="text-slate-500 font-mono text-xs flex items-center justify-end gap-2">
                  On-Chain Data <div className="w-1.5 h-1.5 bg-green-500 rounded-full"></div>
               </div>
             </div>
          </div>
        </motion.div>

        {/* 2. CHALLENGE & SOLUTION GRID */}
        <div className="grid md:grid-cols-12 gap-12 mb-20">
           {/* Left Column: Visual Representation */}
           <div className="md:col-span-5">
              <div className={`h-full min-h-[400px] rounded-3xl border border-white/10 bg-[#0F172A] relative overflow-hidden group`}>
                 {/* Generative Visuals based on ID */}
                 <div className={`absolute inset-0 bg-gradient-to-br ${colors[data.color]} opacity-10`}></div>
                 <div className="absolute inset-0 flex items-center justify-center">
                    <div className={`w-32 h-32 rounded-xl border-2 ${borderColors[data.color]} flex items-center justify-center rotate-45 group-hover:rotate-90 transition-transform duration-700`}>
                       <div className={`w-20 h-20 rounded-full border-2 border-white/20 animate-ping`}></div>
                    </div>
                 </div>
                 
                 {/* Floating Tech Stack Icons */}
                 <div className="absolute bottom-6 left-6 right-6">
                    <div className="text-xs font-bold text-slate-500 uppercase mb-3">Tech Stack</div>
                    <div className="flex gap-3">
                       {['Solidity', 'IPFS', 'Node.js', 'Alchemy'].map((tech) => (
                          <div key={tech} className="px-3 py-1.5 rounded-lg bg-black/40 border border-white/10 text-xs text-white font-mono backdrop-blur-md">
                             {tech}
                          </div>
                       ))}
                    </div>
                 </div>
              </div>
           </div>

           {/* Right Column: Text Content */}
           <div className="md:col-span-7 space-y-12">
              <section>
                <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center ${textColors[data.color]}`}>
                    <Layers className="w-5 h-5" />
                  </div>
                  The Bottleneck
                </h2>
                <p className="text-lg text-slate-300 leading-relaxed pl-2 border-l-2 border-white/5">
                  {data.challenge}
                </p>
              </section>
              
              <section>
                <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center ${textColors[data.color]}`}>
                    <Zap className="w-5 h-5" />
                  </div>
                  The Protocol Solution
                </h2>
                <p className="text-lg text-slate-300 leading-relaxed pl-2 border-l-2 border-white/5">
                  {data.solution}
                </p>
              </section>

              {/* Results List */}
              <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
                 <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-4">Execution Results</h3>
                 <ul className="space-y-4">
                    {data.results.map((result, i) => (
                      <li key={i} className="flex gap-4 text-slate-200">
                        <CheckCircle className={`w-5 h-5 flex-shrink-0 ${textColors[data.color]}`} />
                        {result}
                      </li>
                    ))}
                 </ul>
              </div>
           </div>
        </div>

      </div>
    </div>
  );
};

export default NFTCaseStudyPage;